PT-13059: Add contracts XAPI
VirtoCommerce/vc-module-contract pull request #14
Opened 2023-08-13 21:07 UTC by EugeneOkhriemnko

## Description

## References
### QA-test:

### Jira-link: https://virtocommerce.atlassian.net/browse/PT-13059

### Artifact URL:

2023-08-14 06:49 UTC, OlegoO commented on docs/XAPI.md
> +    carts (
should be contracts

2023-08-14 07:35 UTC, artem-dudarev requested changes

2023-08-14 07:35 UTC, artem-dudarev commented on src/VirtoCommerce.Contracts.ExperienceApi/AssemblyMarker.cs
> +
Remove empty line

2023-08-14 07:35 UTC, artem-dudarev commented on src/VirtoCommerce.Contracts.ExperienceApi/Authorization/ContractAuthorizationHandler.cs
> +            return contact.Organizations.Intersect(memberSearchResult.Results.Select(x => x.Id)).Any();
Need to check more than 20 organizations

2023-08-15 14:09 UTC, artem-dudarev approved these changes

2023-08-18 10:42 UTC, merged